    /*
      Application of setTimeout and setInterval functions.
    */
    /*
      When we click a button:
      1. Computer randomly selects a move.
      2. Compare the moves to get the result.
      3. Update a score.
      4. Display the result in a popup.
    */
      //parse - deserializes JSON string into a JavaScript object
      //if localStorage returns falsy value == null, then scores === 0
      const score = JSON.parse(localStorage.getItem('score')) || {
        wins: 0,
        losses: 0,
        ties: 0,
      }
    /*
    if(!score){
      score={
      wins: 0,
      losses: 0,
      ties: 0,
      }
    }
    */
    updateScoreElement();
    //acts like a switch to control whether the autoplay functionality is on or off.
    let isAutoPlaying = false;
    //since setInterval returns a number, store it to a variabl to keep track.
    let intervalId;
    function autoPlay(){
      //NOT operator (!) to check if isAutplaying is indeed false. If condition will be executed.
      if(!isAutoPlaying){
         intervalId = setInterval(function(){
          //pickComputerMove will return a string wich will then be passed in this variable.
          const playerMove = pickComputerMove();
          //playerMove will be passed as a parameter to allow automated playerMove every 1sec.
          playGame(playerMove);
        }, 3000);
        document.querySelector('.auto-play-button').innerHTML='Stop Playing';
        console.log(`Interval Id: ${intervalId}`);
         isAutoPlaying = true;
      } else {
        /* 
          To stop the setInterval loop:
          *setInterval returns a number.
          *we can use it to stop the interval.
          *when you call setInterval, the browser create a timer and returns a unique identifier (an  integer) that represents that specific timer.This ID is used to manage the isetInterval returns a random-like number which is generated by JavaScript Runtime Environment (like the browser's JavaScript engine).nterval.
          *
        */
        document.querySelector('.auto-play-button').innerHTML='Auto Play';
        clearInterval(intervalId)
        isAutoPlaying = false;
        console.log(`Interval Id: ${intervalId}`)
      }
    }

    document.querySelector('.js-rock-button').addEventListener('click', ()=>{
      playGame('rock');
    });
    document.querySelector('.js-paper-button').addEventListener('click', ()=>{
      playGame('paper');
    })
    document.querySelector('.js-scissors-button').addEventListener('click', ()=>{
      playGame('scissors')
    })
    //To Control Player Pick
    document.body.addEventListener('keydown', (event)=>{
      if(event.key === 'r'){
        playGame("rock");
      }else if(event.key === 'p'){
        playGame ("paper");
      }else if(event.key === "s"){
        playGame("scissors")
      }
      
    });

    function playGame(playerMove){
      //assigns the return value to a var
      //HOISTING
      let computerMove = pickComputerMove();

        let result ='';
        if(playerMove === 'Scissors'){
            if(computerMove === 'Rock'){
                result = 'You lose.';
            }else if(computerMove ==='Paper'){
                result = 'You win.';
            }else if( computerMove = 'Scissors'){
                result = 'Tie.';
            }
        }else if(playerMove === 'Paper'){
            if(computerMove === 'Rock'){
                result = 'You win.'
            }else if(computerMove ==='Paper'){
                result = 'Tie.'
            }else if( computerMove = 'Scissors'){
                result = 'You lose.'
            }
        }else if(playerMove === 'Rock'){
            if(computerMove === 'Rock'){
            result = 'Tie.'
            }else if(computerMove ==='Paper'){
            result = 'You lose.'
            }else if( computerMove = 'Scissors'){
            result = 'You win.'
            }
        }
      

      if (result === 'You win.'){
        score.wins +=1;
      } else if(result === 'You lose.'){
        score.losses +=1;
      }else if(result ==='Tie.'){
        score.ties +=1;
      }
      console.log(playerMove);

      //(name, value)
      //localStorage only accepts 'string'
      localStorage.setItem('score', JSON.stringify(score));
      // example: { wins: 2, losses: 1, ties: 3 } >> {"wins":2,"losses":1,"ties":3}

      updateScoreElement();
      //results
      document.querySelector('.js-result').innerHTML = `${result}`;
      //picks
      document.querySelector('.js-moves').innerHTML = `You 
          <img src="/10-DOM-CSS/imgs/${playerMove}-emoji.png" alt="playerMove" class="move-icon">
          <img src="/10-DOM-CSS/imgs/${computerMove}-emoji.png" alt="computerMove" class="move-icon">
          Computer`; 
    }

    // Scores
    function updateScoreElement(){
        document.querySelector('.js-score').innerHTML = `Wins: ${score.wins}, Losses: ${score.losses}, Ties:${score.ties}`;
    }

    //Computer Move
    //returns a string
    function pickComputerMove() {
      const randomNumber = Math.random();
      let computerMove = "";
      if (randomNumber >= 0 && randomNumber < 1 / 3) {
        computerMove = "Rock";
      } else if (randomNumber >= 1 / 3 && randomNumber < 2 / 3) {
        computerMove = "Paper";
      } else if (randomNumber >= 2 / 3 && randomNumber < 1) {
        computerMove = "Scissors";
      }
      return computerMove;
    }
    
    //12U
    //To Control Autoplay function.
    document.body.addEventListener('keydown', (even)=>{
      if(event.key === 'a'){
        autoPlay();
      }
    });
    //12V and 12x
    document.querySelector('.reset-score-button').addEventListener('click',()=>{
      document.querySelector('.reset-confirmation').innerHTML = `
      <p> Are you sure you want to reset the score</p>
      <button onclick="
      score.wins = 0;
      score.losses = 0;
      score.ties = 0;
      localStorage.removeItem('score');
      updateScoreElement();">Yes</button>
      <button onclick="
      document.querySelector('.reset-confirmation').innerHTML = '';
      ">No</button>
      `
      ;
    });
    //12W and 12x
    document.body.addEventListener('keydown',(event)=>{
      if(event.key === 'Backspace' ){
        document.querySelector('.reset-confirmation').innerHTML = `
        <p> Are you sure you want to reset the score</p>
        <button onclick="
        score.wins = 0;
        score.losses = 0;
        score.ties = 0;
        localStorage.removeItem('score');
        updateScoreElement();">Yes</button>
        <button onclick="
        document.querySelector('.reset-confirmation').innerHTML = '';
        ">No</button>
        `
      }
    })